# github actions for Pull Request
name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download t2421 github action
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: t2421/t2421-gh-actions
          path: .github/actions/t2421

      - uses: ./.github/actions/t2421/setup-npmrc
        with:
          auth_token: ${{ secrets.GH_TOKEN }}